// <auto-generated />
namespace SportsClub.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class _2803 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2803));
        
        string IMigrationMetadata.Id
        {
            get { return "202503281005411_2803"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
